//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int NumberRating { get; set; }
        public Nullable<int> Film_ID { get; set; }
        public Nullable<int> Reviewer_ID { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Reviewer Reviewer { get; set; }
    }
}
